/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.awt.AWTUtilities;


/**
 *
 * @author sebas
 */
public class vIndex extends javax.swing.JFrame {

    /**
     * Creates new form p
     */
    private final int  delay = 3 ;
    private vMenu menu = null;


    public vIndex() {
        
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        
       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLoading = new javax.swing.JLabel();
        imgfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gif/loading.gif"))); // NOI18N
        getContentPane().add(imgLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 930, 60));

        imgfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/main.png"))); // NOI18N
        getContentPane().add(imgfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded

    }//GEN-LAST:event_formComponentAdded

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println("Se abrió formulario");
        
        Thread f = new Thread(){
            public void start(){
                try {
                    menu = new vMenu();
                    System.out.println("[Thread] - Form Menu");
                    Thread.sleep(delay*1000);   // Espera 5 Segundos
                    
                    menu.setLocationRelativeTo(null);
                    setVisible(false);
                    menu.setVisible(true);
                } catch (Exception e) {
                    System.out.println("No se ejcuto hilo: "+e);
                }
            }        
        };
        f.start();
        
        
    }//GEN-LAST:event_formWindowOpened
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLoading;
    private javax.swing.JLabel imgfondo;
    // End of variables declaration//GEN-END:variables
}
